# Generated by Django 6.0.6 on 2026-06-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
    ]
